#!/bin/bash

SCRIPT=$(basename "${BASH_SOURCE[0]}")

VMINFO () {
    for vm in $(sudo virsh list | awk '/running/ {print $2}')
    do
        RESULT=$(virsh domifaddr "$vm" --source agent 2> /dev/null|grep -v 127 | grep -E "([0-9]{1,3}[\.]){3}[0-9]{1,3}")
        IP=$(echo "${RESULT}" | grep -v 127 | grep -E -o "([0-9]{1,3}[\.]){3}[0-9]{1,3}")
        INTERFACE=$(echo "${RESULT}" | awk '{print $1}')
        MAC=$(echo "${RESULT}" | awk '{print $2}')
        NETWORK=$(echo "${RESULT}" | awk '{print $4}')
        _NETWORK=$(echo $NETWORK| awk '{print $1}')

        if [ "A${INTERFACE}" == "A" ]
        then
            VM_IFACE="none"
        else
            VM_IFACE=$(echo $INTERFACE| awk '{print $1}')
        fi

        if [ "A${MAC}" == "A" ]
        then
            VM_MAC="none"
        else
            VM_MAC=$(echo $MAC| awk '{print $1}')
        fi

        if [ "A${IP}" == "A" ]
        then
            VM_IP="none"
        else
            VM_IP=$(echo $IP | awk '{print $1}')
        fi

        if [ "A${NETWORK}" == "A" ]
        then
            VM_NETMASK="none"
            VM_PREFIX="none"
            VM_NETWORK="none"
        else
            VM_NETMASK=$(ipcalc -m $_NETWORK|awk -F= '{print $2}')
            VM_PREFIX=$(ipcalc -p $_NETWORK|awk -F= '{print $2}')
            VM_NETWORK=$(ipcalc -n $_NETWORK|awk -F= '{print $2}')
        fi
        echo "$vm,$VM_IP,$VM_IFACE,$VM_MAC,$VM_NETWORK,$VM_NETMASK,$VM_PREFIX,$KVMHOST,$KVMHOST_IP"
    done
}

HOSTNAME=$(hostname)
KVMHOST_IP=$(ip route get 8.8.8.8 | awk -F"src " 'NR==1{split($2,a," ");print a[1]}')
KVMHOST=$(hostname -s)

echo "VM Name,IP,Interface,Mac,Network,Netamsk,Prefix,KVM Host,KVM Host IP"
VMINFO

exit 0
