---
#playbook.yaml

- name: DISPLAY THE INVENTORY VARS
  hosts: all
  gather_facts: no
  tasks:
    - name: display host info
      debug:
        msg: "The mgmt IP is {{ ansible_host }} and kvmhost is {{ ansible_kvmhost }}"
